language: elixir
elixir:
  - 1.3
otp_release:
  - 18.3

env:
  - WEBDRIVER=selenium

addons:
  postgresql: "9.4"

before_script:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - bash $TRAVIS_BUILD_DIR/test/tools/start_webdriver.sh

script: mix test
